yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: node-modules
packageExtensions:
  "@babel/plugin-proposal-decorators@*":
    peerDependencies:
      "@babel-core": "*"
  "styled-components":
    peerDependencies:
      "react-is": "*"