yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: node-modules
packageExtensions:
  "@babel/plugin-proposal-decorators@*":
    dependencies:
      "@babel/core": "*"
  "@babel/plugin-transform-react-jsx@*":
    dependencies:
      "@babel/core": "*"
  "@babel/preset-env@*":
    dependencies:
      "@babel/core": "*"
  "styled-components@*":
    dependencies:
      "react-is": "*"
  "jscodeshift@*":
    dependencies:
      "@babel/preset-env": "*"